### PR TITLE
FastAPI: Improve detect request body

### PR DESCRIPTION
**Pull request by theusaf**
* Binary files can be directly uploaded
* Adds a depth map to the pydantic model, although not used anywhere at the moment
* When making requests, optional fields can be left out of the multipart/form-data body

### CODE REVIEW

**Review by stalberm — CHANGES_REQUESTED** [review]
Testing this on the ec2 server by taking an image from the device and sending it, it does not work. The device immediately returns. Development branch does currently work though; Did you test using the nano? (I'm running off the pi atm)

**Comment by stalberm** [comment]
@theusaf 
Looking at docker logs heres the error:
"POST /api/model/detect HTTP/1.1" 422 Unprocessable Entity

**Comment by theusaf** [comment]
> Testing this on the ec2 server by taking an image from the device and sending it, it does not work. The device immediately returns. Development branch does currently work though; Did you test using the nano? (I'm running off the pi atm)

Tested using the following code (latest nano branch on embedded repo)
```py
from food_waste.api import ImageApi, MissingSecretsError, RequestFailedError
import httpx
import asyncio
import os

httpx_client = httpx.AsyncClient(timeout=60.0)
image_api = ImageApi(
  httpx_client,
  "http://localhost:3000"
)

os.environ["API_KEY"] = "sample_api_key"

async def main():
  loop = asyncio.get_event_loop()
  await image_api.post_image(
    "example.jpeg",
    "foo",
    1.0
  )

loop = asyncio.get_event_loop()
try:
  loop.run_until_complete(main())
except Exception as e:
  print("An error ocurred during execution", e)
```

**Comment by stalberm** [comment]
Awesome, figured me using the pi and it's code could be the issue. Thanks for confirming

**Review by stalberm — APPROVED** [review]

**Review by kimberlymarkley — APPROVED** [review]

**Pull request merged**
